Implement posting and viewing internships
ecellju/internship-portal pull request #27
Opened 2018-03-03 15:33 UTC by in42

- Add submit post form component

2018-03-03 17:26 UTC, akashsahaju reviewed
Looks like it isn't working
![image](https://user-images.githubusercontent.com/17269147/36937226-2711b406-1f36-11e8-8127-201a450e5dad.png)

2018-03-04 12:47 UTC, in42 commented
@akashsahaju I haven't implemented the ajax call yet.

2018-03-04 13:28 UTC, akashsahaju commented
Ok. The UI looks good.

2018-03-07 15:43 UTC, sagnikm95 commented on app/admin/components/post/SubmitPostForm.js
> +            placeholder="Enter the number of months..."
let the type be string so without that increment option [ so that unit of  duration can be mentioned]

2018-03-07 16:07 UTC, sagnikm95 requested changes
Implement postView for both admin and user side

2018-03-07 16:07 UTC, sagnikm95 commented on app/admin/components/post/SubmitPostForm.js
> +            placeholder="Enter the stipend..."
again let it be string

2018-03-07 16:07 UTC, sagnikm95 commented on app/admin/components/post/SubmitPostForm.js
> +          rows="5"
Instead of description have three separtate fields abt the internship, who can apply, perks

2018-03-07 16:07 UTC, sagnikm95 commented on app/admin/post/PostItem.js
>  import React from 'react';
Why have this as well as another exactly same post item component in app/common

2018-03-10 06:19 UTC, merged